### ISSUE TITLE
Deploying Office-Addin-Taskpane-SSO to host

### ISSUE THREAD

**Issue by Mike-tech** [OfficeDev/Office-Addin-Taskpane-SSO#19]
Hi there

I have this office addin template installed and configured. It works fine locally including the SSO. But when I deploy the addin using the deployment documentation [here ](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code). When I tried to run the manifest when running from the deployed Azure static website, the SSO doesn't work. I get 404:
GET https://myhostname.web.core.windows.net/auth?_=1603205168265 404 (The requested content does not exist.)

I have a feeling a static website host is not for sso application. Can you advise what hosting should be used for this template?

Thanks

**Comment by TCourtneyOwen** [comment]
Looping in a couple folks.  @Rick-Kirkham @ElizabethSamuel-MSFT

**Comment by ElizabethSamuel-MSFT** [comment]
@davidchesnut Can you take a look? Thx.

**Comment by Mike-tech** [comment]
Closing this as I have the same issue at [https://github.com/OfficeDev/office-js-docs-pr/issues/2279](https://github.com/OfficeDev/office-js-docs-pr/issues/2279). So follow from there.
