### ISSUE TITLE
Office Addin SSO TaskPane is throwing 500 error when exchanging Bootstrap token

### ISSUE THREAD

**Issue by dheerajbalmuri** [OfficeDev/Office-Addin-Taskpane-SSO#36]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

When i hit "Get my user information" button from task pane it shows get the token and update the word with  my user profile info.

# Current behavior

Followed the exact steps mentioned in the [article ](https://docs.microsoft.com/en-us/learn/modules/office-add-ins-sso/3-exercise-word-sso). When i hit Get my user information button from task pane it throw's the following message on the debug console "Failed to load resource: the server responded with a status of 500 (Internal Server Error) [https://localhost:3000/auth?_=1621883133463]"

When i was debugging the project i found that the application is failing when exchanging the bootstrap token with the graph access token with the following error. 

""{"message":"invalid json response body at https://login.microsoftonline.com/common/oauth2/v2.0/token reason: Unexpected token < in JSON at position 0","type":"invalid-json"}""

## Steps to Reproduce

Clone the Project , run npm configure-sso and npm start .

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Node version: 14.16.0
* Office version: Version 2013 (Build 13901.20516 click to run)
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by millerds** [comment]
Can you me more specific about what you are doing when you follow the article?  I can follow the basics of it (I skip navigating the azure pages to look at what the script did) and it works fine.

**Comment by millerds** [comment]
If you have any further comments please re-open.
