### ISSUE TITLE
Error get Graph data. ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by mrcpgn** [OfficeDev/Office-Addin-Taskpane-SSO#49]
Node version: 14.17.0
TypeScript Version: 4.4.3
Visual Studio Code

# Current behavior

I'm trying to create my first SSO Office Add-in with Typescript for Outlook).
Everything works fine with the default code.
I can retrieve the profile information and write it in the body of the email.
But when I try to make a call to Graph,
then changing from:
`const response: any = await sso.makeGraphApiCall (exchangeResponse.access_token);`
to:
`const endpoint = "/me/";`
`const urlParams = "?$select = displayName";`
`const response = await sso.getGraphData (exchangeResponse.access_token, endpoint, urlParams);`

I get the error: "**Error get Graph data. ReferenceError: Buffer is not defined**"

Can someone help me?
Many thanks in advance

## Steps to Reproduce

yo office
> Office Add-in Task Pane project supporting single sign-on 
> TypeScript
> Outlook

 npm run configure-sso

package.json:
`{`
`  "name": "office-addin-taskpane-sso",`
`  "version": "0.0.0",`
`  "private": true,`
`  "config": {`
`    "app_to_debug": "outlook",`
`    "app_type_to_debug": "desktop",`
`    "dev_server_port": 3000`
`  },`
`  "scripts": {`
`    "build": "webpack --mode production",`
`    "build:dev": "webpack --mode development",`
`    "configure-sso": "office-addin-sso configure manifest.xml",`
`    "dev-server": "webpack serve --mode development",`
`    "lint": "office-addin-lint check",`
`    "lint:fix": "office-addin-lint fix",`
`    "prettier": "office-addin-lint prettier",`
`    "sideload": "office-addin-debugging start manifest.xml",`
`    "start": "npm run build:dev && concurrently \"npm run start:server\"",`
`    "start:server": "office-addin-sso start manifest.xml",`
`    "stop": "office-addin-debugging stop manifest.xml",`
`    "validate": "office-addin-manifest validate manifest.xml",`
`    "watch": "webpack --watch --mode development"`
`  },`
`  "dependencies": {`
`    "core-js": "^3.9.1",`
`    "dotenv": "^8.2.0",`
`    "msal": "^1.3.2",`
`    "node-fetch": "^2.6.1",`
`    "office-addin-sso": "^1.1.2",`
`    "regenerator-runtime": "^0.13.7"`
`  },`
`  "devDependencies": {`
`    "@babel/core": "^7.13.10",`
`    "@babel/preset-typescript": "^7.13.0",`
`    "@types/jquery": "^3.3.31",`
`    "@types/office-js": "^1.0.180",`
`    "@types/office-runtime": "^1.0.17",`
`    "acorn": "^8.5.0",`
`    "babel-loader": "^8.2.2",`
`    "buffer": "^6.0.3",`
`    "concurrently": "^5.2.0",`
`    "copy-webpack-plugin": "^9.0.1",`
`    "eslint": "^7.20.0",`
`    "eslint-plugin-office-addins": "^1.0.1",`
`    "file-loader": "^6.2.0",`
`    "html-loader": "^2.1.2",`
`    "html-webpack-plugin": "^5.3.2",`
`    "https-browserify": "^1.0.0",`
`    "office-addin-cli": "^1.2.3",`
`    "office-addin-debugging": "^4.2.3",`
`    "office-addin-dev-certs": "^1.6.3",`
`    "office-addin-lint": "^1.3.3",`
`    "office-addin-manifest": "^1.6.3",`
`    "office-addin-prettier-config": "^1.1.0",`
`    "source-map-loader": "^3.0.0",`
`    "stream-http": "^3.2.0",`
`    "ts-loader": "^9.2.5",`
`    "typescript": "^4.3.5",`
`    "webpack": "^5.50.0",`
`    "webpack-cli": "^4.8.0",`
`    "webpack-dev-server": "4.1.1"`
`  },`
`  "prettier": "office-addin-prettier-config"`
`}`

**Comment by millerds** [comment]
Try using graph explorer to verify you're call: https://developer.microsoft.com/en-us/graph/graph-explorer

**Comment by millerds** [comment]
@mrcpgn are you still encountering issues?
