### ISSUE TITLE
Getting 504 error during Bootstrap tokken exchange 

### ISSUE THREAD

**Issue by Callmeksk** [OfficeDev/Office-Addin-Taskpane-SSO#54]
I am trying to create add-in supporting SSO with JavaScript,

After side loading the add-in into outlook, it successfully displays the taskpane but when I try to retrieve user information by clicking the provided button it is giving **504 timeout** with the requesting URL and throwing unhandled promise rejection   Error: getaddrinfo EAI_AGAIN graph.microsoft.com in the console.

After debugging, I found out, the error is coming from function **makeGraphApiCall** in **ms-graphhelper.js** inside node modules, when trying to call **getuserdata**.

When trying to access the url in browser it is giving **504 Gateway  timeout**
I am attaching the error snaps thrown in console.

Thanks in advance!!

![image](https://user-images.githubusercontent.com/42495076/145403678-fc4ed13c-efc5-4c1a-adab-30fda9a5de63.png)

![image](https://user-images.githubusercontent.com/42495076/145403215-6b245ee2-a6b2-43d8-9c7f-11a7bc4917ef.png)

**Comment by millerds** [comment]
Can you provide more details about the project?  Is this straight out of 'yo office' or have you made some changes to it afterwards?
